### Creates report 
POST http://localhost:4004/api/reports/create
Content-Type: application/json

{
  "price": 34000,
  "make": "Landrover",
  "model": "Unirover",
  "year": 2022,
  "lng": 0,
  "lat": 0,
  "mileage": 9912
}
